name: surveillance-enhancement
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10
  
  # Core ML/AI Libraries
  - pytorch>=2.0.1
  - torchvision>=0.15.2
  - torchaudio>=2.0.2
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  
  # Computer Vision
  - opencv>=4.8.0
  - pillow>=9.5.0
  - scikit-image>=0.21.0
  - imageio>=2.31.0
  
  # Web Framework
  - flask>=2.3.0
  - flask-cors>=4.0.0
  - werkzeug>=2.3.0
  - waitress>=2.1.0
  
  # Scientific Computing
  - numpy>=1.24.0
  - scipy>=1.11.0
  - matplotlib>=3.7.0
  
  # Utilities
  - requests>=2.31.0
  - tqdm>=4.65.0
  - pyyaml>=6.0
  - psutil>=5.9.0
  
  # Development Tools
  - pytest>=7.4.0
  - black>=23.0.0
  - flake8>=6.0.0
  - pre-commit>=3.3.0
  
  # Logging and Monitoring
  - loguru>=0.7.0
  
  # File Handling
  - pathlib2
  - chardet>=5.1.0
  
  # Pip dependencies (not available via conda)
  - pip
  - pip:
    # Face Enhancement Models
    - gfpgan>=1.3.8
    - realesrgan>=0.3.0
    - basicsr>=1.4.2
    - facexlib>=0.3.0
    
    # Additional ML libraries
    - timm>=0.9.0
    - einops>=0.6.1
    
    # Web UI enhancements
    - flask-uploads>=0.2.1
    - flask-wtf>=1.1.0
    - wtforms>=3.0.0
    
    # Image processing
    - piexif>=1.1.3
    - rawpy>=0.18.0
    
    # Model management
    - huggingface-hub>=0.16.0
    - transformers>=4.32.0
    
    # Performance monitoring
    - psutil>=5.9.0
    - gpustat>=1.1.0
    
    # Additional forensic tools
    - hashlib-compat>=1.0.0
    - python-magic>=0.4.27
    
    # Testing and quality
    - pytest-cov>=4.1.0
    - pytest-mock>=3.11.0